print("Enter the number of lives:")
life = int(input())
print("Enter the energy level:")
energy = int(input())
print("Enter the \"shield\" level:")
shield = int(input())
print("\nHealth has been set:")
print("\nLives: ", "\u2665"*life)
print("\nEnergy: ", "\u2666"*energy)
print("\nShield: ", "\u2666"*shield)