print("What is your name, human?")
name = input()
print("How old are you?(in years)?")
age = int(input())
print("How tall are you (in meters)?")
Height = float(input())
print("How much do you weigh (in kilograms)?")
weight = float(input())
bmi = weight/(Height**2)
print(f"{name} you are {age} years old. Your bmi is {bmi:2f}")